---
- hosts: VM
  tasks:
    - name: Install nginx
      apt: name=nginx state=latest
    - name: Install Mariadb
      apt: name=mariadb-server state=latest
    - name: Install tree
      apt: name=tree state=latest
    - name: Upgrade
      apt: upgrade=yes
    - name: Install HTTPD on Ubuntu
      apt: name=apache2 update_cache=yes state=latest
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
